{
  "name": "mybutton",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "type": "module",
  "license": "AGPL-version-3.0",
  "private": false,
  "engines": {
    "node": ">= 14.0.0",
    "npm": ">= 6.0.0"
  },
  "homepage": "http://",
  "repository": {
    "type": "git",
    "url": ""
  },
  "bugs": "",
  "keywords": [],
  "author": {
    "name": "",
    "email": "",
    "url": ""
  },
  "contributors": [],
  "scripts": {
    "dev": "treebtc",
    "test": "rococo"
  },
  "devDependencies": {
    "rollup": "^4.6.1",
    "typescript": "^5.3.2"
  },
  "dependencies": {
    "@alchemy/aa-accounts": "^1.2.0",
    "@alchemy/aa-alchemy": "^1.2.0",
    "@alchemy/aa-core": "^1.2.0",
    "viem": "^1.19.9"
  }
}
